CREATE TABLE  "USERTABLE" 
   ( "ID" VARCHAR2(32) NOT NULL ENABLE, 
 "PASSWD" VARCHAR2(32) NOT NULL ENABLE, 
 "NAME" VARCHAR2(32) NOT NULL ENABLE, 
 "RRNUM" VARCHAR2(32) NOT NULL ENABLE, 
 "TEL" VARCHAR2(20), 
 "MAILNUM" VARCHAR2(20), 
 "ADDRESS" VARCHAR2(50), 
 "EMAIL" VARCHAR2(20), 
 "DOMAIN" VARCHAR2(20), 
 "FORGETQ" VARCHAR2(100) NOT NULL ENABLE, 
 "FORGETA" VARCHAR2(100) NOT NULL ENABLE, 
  CONSTRAINT "USERTABLE_PK" PRIMARY KEY ("ID") ENABLE
  
   );