CREATE TABLE  "SCHEDULE" 
   ( "SCHENUM" NUMBER, 
 "ID" VARCHAR2(20), 
 "TITLE" VARCHAR2(50), 
 "CONTENT" VARCHAR2(400), 
 "PUBLISH" VARCHAR2(20), 
 "SDATE" DATE, 
 "EDATE" DATE, 
 "TYPE" VARCHAR2(20), 
  CONSTRAINT "SCHEDULE_PK" PRIMARY KEY ("SCHENUM") ENABLE
   )